### ISSUE TITLE
Can stats.kiwix.org be behind the reverse proxy?

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#18]
Even if we use an other docker-compose file?

**Comment by florentk** [comment]
That's what I thought at the base, I had specify in the docker-compose of matomo-server to join the network created by the docker-compose "kiwix", otherwise it does not work because it creates two distinct networks. So,  we have two docker-compose files but with a common network.
For moment, I had disabled the HTTP redirect for test

**Comment by kelson42** [comment]
@florentk merci
