### ISSUE TITLE
Scanning mirrors with mirrorbrain is too long

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#25]
Should take a few dozens of minutes and it seems to take days.

**Comment by florentk** [comment]
mirrobrain scan seem block in connect to mirror.download.kiwix.org because the IP resolved is an external IP and not the ip of docker container on the server. I have configure more properly a new network to match the mirror.download.kiwix.org domain name with reverse-proxy container IP. Fix in eb145a3

**Comment by kelson42** [comment]
@florentk well done.
