### ISSUE TITLE
Kiwix & openZIM wikis are very slow

### ISSUE THREAD

**Issue by florentk** [kiwix/maintenance#47]
Need more RAM :

```
$ sloppy stats openzim 
CONTAINER 		 CPU % 	 MEM / LIMIT 		 MEM % 	 NET I/O Extern 	 NET I/O Intern
openzim/wiki-ad4ada 	 0.4% 	 960 MiB / 960 MiB 	 100.0%  410 B / 2.39 KiB 	 10.9 B / 0 B
```

**Comment by kelson42** [comment]
@florentk Have added quite a bit more RAM to both wikis, should be enough.

**Comment by kelson42** [comment]
I reopen the problem as the problem is still there and impacts wiki.kiwix.org. It seems we have at least identified one problem https://github.com/openzim/mediawiki-docker/issues/17. But the problem is more general. I'm asking myself if the problem is not simply that the sqlite backend just struggle to work properly with concurrent requests. @legoktm Here too, your help might be really welcome.

**Comment by kelson42** [comment]
This has been fixed
