### ISSUE TITLE
All visitors have a same IP on Sloppy 

### ISSUE THREAD

**Issue by florentk** [kiwix/maintenance#48]
When I receive mail confirmation, the IP adresse is always the same : 192.168.18.27. Then the limite of 99 account creation is reacheable in 24 hours, and nobody can create a new account. Maybe a bot creates accounts.

**Comment by kelson42** [comment]
@florentk This is a Mediwiki configuration problem. The reason is probably that the IP comes from the reverse proxy. Reverse proxies used to set a specific additional HTTP header like for example https://en.wikipedia.org/wiki/X-Forwarded-For. We should condigure Mediawiki to rely on it instead of the real IP. Have a look to https://www.mediawiki.org/wiki/Manual:$wgUsePrivateIPs/fr

**Comment by florentk** [comment]
@kelson42 ok ! I can modify that in the image, but we must change by hand LocalSettings.custom.php file on Sloppy volume (I have no access)

**Comment by florentk** [comment]
@kelson42 strange, I have already this line in LocalSettings.php `$wgUsePrivateIPs = true;`

**Comment by florentk** [comment]
@kelson42 Add `192.168.18.0/24` to `wgSquidServers` in LocalSettings.custom.php ? You have to do that by hand in the Sloppy volume.

**Comment by kelson42** [comment]
@florentk I have fixed both problem with custom conf change and also in mediawiki-docker.
